// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/gulp-typedoc/gulp-typedoc.d.ts
declare module "gulp-typedoc" {
    interface Options {
        out: string;
        mode?: string;
        json?: string;
        exclude?: string;
        includeDeclarations?: boolean;
        externalPattern?: string;
        excludeExternals?: boolean;
        module?: string;
        target?: string;
        theme?: string;
        name?: string;
        readme?: string;
        hideGenerator?: boolean;
        gaID?: string;
        gaSite?: string;
        verbose?: boolean;
    }

    function typedoc(opts: Options): NodeJS.ReadWriteStream;
    export = typedoc;
}
