// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/gulp-cached/gulp-cached.d.ts
declare module "gulp-cached"
{
    interface ICacheStore
    {
        [name: string]: {};
    }

    interface IOptions
    {
        /**
         * Uses md5 instead of storing the whole file contents.
         * @default false
         */
        optimizeMemory?: boolean;
    }

    interface IGulpCached
    {
        /**
         * Creates a new cache hash or uses an existing one.
         */
        (name: string, options?: IOptions): NodeJS.ReadWriteStream;

        /**
         * Cache store.
         */
        caches: ICacheStore;
    }

    const cached: IGulpCached;
    export = cached;
}
